### ISSUE TITLE
miui稳定版 开发者选项USB调试（安全设置）可以通过工具或者命令打开吗

### ISSUE THREAD

**Issue by dixtdf** [liuran001/GJZS#13]
我手机sim卡槽坏了，没法直接打开，打开它必须插入sim卡

**Comment by dixtdf** [comment]
https://f5.pm/go-41358.html
我找到hook的办法了，但是不太会搞。。。

**Comment by dixtdf** [comment]
https://www.52pojie.cn/thread-1282827-1-1.html
https://gist.github.com/LeadroyaL/98d35f526c44d86b379a7099f6f823e6
又发现一个解决办法，希望作者可以加到功能列表里去，这个功能很有用

**Comment by liuran001** [comment]
@dixtdf hook的方法的话得找大佬做模块，我能力不够，恕我没法解决这个问题
修改配置文件办法的话看原文的图应该是miui9，在新版的系统上我不确定是否有效，这需要我测试之后再给出答案

**Comment by dixtdf** [comment]
貌似miui12.5已经不行了，我正在试，那我想想办法看能不能搞个模块
