### ISSUE TITLE
在 开机页面专区 遇到了一些问题。

### ISSUE THREAD

**Issue by SteveZMTstudios** [liuran001/GJZS#16]
我正在使用的设备是华为 荣耀畅玩5X KIW-TL00
官方rom解开bl magisk root 已刷入twrp 搞机助手已授权root
开机页面专区中 自定义第一屏/fastboot界面>生成配置选项
点进去后弹出窗口没有可以选择的img，即点击右边的小箭头没有出现任何候选项。

在这之前除解开bl锁以外未使用任何程序及模块修改过bootloader

这也许是一个问题？我需要思考和帮助。

ps：如果这个issue有点机翻的话，那可能是因为GitHub的语言环境😀

**Comment by liuran001** [comment]
@SteveZMTstudios 不显示即为不支持，我没有相同机型也没法进行测试，如果您发现有其他方法可以正常解包和打包，可以告诉我，我会尽量去修复

**Comment by SteveZMTstudios** [comment]
系统版本EMUI 4.0.3
安卓版本6.0.1
（是的我能理解这个版本实在太旧了以至于很难找到相关的配置文件，而且这是一个个性化功能，相关重要性低于其他模块功能。但是我还是希望能获得相关技术支持，因为我同时也找不到root目录下的boot.img（悲））

**Comment by ZXGU183** [comment]
华为的boot分区名为ramdisk（你刷了TWRP应该知道刷进recovery_ramdisk分区了）另搞机助手没有适配华为的分区表，你可以把分区表发出来研究
